package services

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"simple-bind9-panel/config"
	"simple-bind9-panel/database"
	"simple-bind9-panel/models"
)

// Init 初始化服务
func Init() {
	log.Println("BIND9 Panel services initialized")
}

// GetServerStatus 获取服务器状态
func GetServerStatus() *models.ServerStatus {
	status := &models.ServerStatus{
		Running: false,
	}

	// 检查 named 进程是否运行
	cmd := exec.Command("pgrep", "-x", "named")
	if err := cmd.Run(); err == nil {
		status.Running = true
	}

	// 获取版本
	out, err := exec.Command("named", "-v").Output()
	if err == nil {
		status.Version = strings.TrimSpace(string(out))
	}

	return status
}

// RestartNamed 重启 BIND
func RestartNamed() error {
	// 使用 killall 让 systemd 自动重启 (需要 sudo)
	cmd := exec.Command("sudo", "killall", "named")
	output, err := cmd.CombinedOutput()
	if err != nil {
		// 如果 sudo 失败，尝试直接运行
		cmd = exec.Command("killall", "named")
		output, err = cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("failed to restart named: %s", string(output))
		}
	}
	log.Println("BIND9 restarted")
	return nil
}

// ReloadNamed 重载配置
func ReloadNamed() error {
	// 优先使用系统的 rndc，如果权限不足则尝试 sudo
	cmd := exec.Command("sudo", config.RNDCPath, "reload")
	output, err := cmd.CombinedOutput()
	if err != nil {
		// 如果 sudo 失败，尝试直接运行（以防已经以 root 运行）
		cmd = exec.Command(config.RNDCPath, "reload")
		output, err = cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("failed to reload named: %s", string(output))
		}
	}
	log.Println("BIND9 config reloaded")
	return nil
}

// ValidateConfig 验证配置语法
func ValidateConfig(content string) error {
	// 创建临时文件
	tmpFile := filepath.Join(os.TempDir(), "named-checkconf-"+time.Now().Format("20060102-150405"))
	if err := os.WriteFile(tmpFile, []byte(content), 0644); err != nil {
		return err
	}
	defer os.Remove(tmpFile)

	// 运行 named-checkconf
	cmd := exec.Command("named-checkconf", tmpFile)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s", string(output))
	}
	return nil
}

// CreateBackup 创建配置备份
func CreateBackup(name string) error {
	content, err := os.ReadFile(config.NamedConf)
	if err != nil {
		return err
	}

	filename := name + ".conf"
	backupPath := filepath.Join(config.BackupDir, filename)

	if err := os.WriteFile(backupPath, content, 0644); err != nil {
		return err
	}

	// 记录到数据库
	backup := &models.ConfigBackup{
		ID:        uint(time.Now().UnixNano()),
		Name:      name,
		FilePath:  backupPath,
		CreatedAt: time.Now(),
	}
	database.DB.Backups = append(database.DB.Backups, *backup)
	database.Save(config.DBPath)

	log.Printf("Backup created: %s", backupPath)
	return nil
}

// CreateZoneFile 创建区域文件
func CreateZoneFile(zone models.Zone) error {
	if zone.File == "" {
		zone.File = fmt.Sprintf("/var/cache/bind/db.%s", zone.Name)
	}

	// 生成区域文件内容
	content := generateZoneFile(zone)

	if err := os.WriteFile(zone.File, []byte(content), 0644); err != nil {
		return err
	}

	return nil
}

// UpdateZoneFile 更新区域文件
func UpdateZoneFile(zone models.Zone) error {
	content := generateZoneFile(zone)

	if err := os.WriteFile(zone.File, []byte(content), 0644); err != nil {
		return err
	}

	return nil
}

// DeleteZoneFile 删除区域文件
func DeleteZoneFile(zone models.Zone) error {
	if zone.File != "" {
		os.Remove(zone.File)
	}
	return nil
}

// generateZoneFile 生成 zone file 内容
func generateZoneFile(zone models.Zone) string {
	var sb strings.Builder
	serial := time.Now().Format("2006010215")

	sb.WriteString(fmt.Sprintf("$TTL 86400\n"))
	sb.WriteString(fmt.Sprintf("@\tIN\tSOA\tns1.%s. admin.%s. (\n", zone.Name, zone.Name))
	sb.WriteString(fmt.Sprintf("\t\t\t\t%s\t; Serial\n", serial))
	sb.WriteString(fmt.Sprintf("\t\t\t\t3600\t; Refresh\n"))
	sb.WriteString(fmt.Sprintf("\t\t\t\t1800\t; Retry\n"))
	sb.WriteString(fmt.Sprintf("\t\t\t\t604800\t; Expire\n"))
	sb.WriteString(fmt.Sprintf("\t\t\t\t86400 )\t; Minimum TTL\n"))
	sb.WriteString(fmt.Sprintf("\n"))
	sb.WriteString(fmt.Sprintf("@\tIN\tNS\tns1.%s.\n", zone.Name))
	sb.WriteString(fmt.Sprintf("@\tIN\tA\t127.0.0.1\n"))
	sb.WriteString(fmt.Sprintf("\n"))

	// 添加数据库中的记录
	for _, r := range database.DB.Records {
		if r.ZoneID != zone.ID || !r.Enabled {
			continue
		}
		if r.Type == "MX" {
			sb.WriteString(fmt.Sprintf("%s\t%d\tIN\t%s\t%d\t%s\n", r.Name, r.TTL, r.Type, r.Priority, r.Value))
		} else if r.Type == "SRV" {
			sb.WriteString(fmt.Sprintf("%s\t%d\tIN\t%s\t%d\t%s\n", r.Name, r.TTL, r.Type, r.Priority, r.Value))
		} else {
			sb.WriteString(fmt.Sprintf("%s\t%d\tIN\t%s\t%s\n", r.Name, r.TTL, r.Type, r.Value))
		}
	}

	return sb.String()
}

// UpdateForwardersConfig 更新 BIND 转发配置
func UpdateForwardersConfig() error {
	// 生成转发配置文件
	var sb strings.Builder
	sb.WriteString("// DNS Forwarders Configuration\n")
	sb.WriteString("// Generated by Simple BIND9 Panel\n\n")

	// 全局转发器
	var globalForwarders []string
	var domainForwards []models.Forwarder

	for _, f := range database.DB.Forwarders {
		if !f.Enabled {
			continue
		}
		if f.Domains == "" {
			// 全局转发器
			globalForwarders = append(globalForwarders, f.Servers)
		} else {
			// 域名特定转发
			domainForwards = append(domainForwards, f)
		}
	}

	// 如果有全局转发器，添加到配置
	if len(globalForwarders) > 0 {
		sb.WriteString("options {\n")
		sb.WriteString("    forward only;\n")
		sb.WriteString("    forwarders {\n")
		for _, servers := range globalForwarders {
			for _, ip := range strings.Split(servers, ",") {
				ip = strings.TrimSpace(ip)
				if ip != "" {
					sb.WriteString(fmt.Sprintf("        %s;\n", ip))
				}
			}
		}
		sb.WriteString("    };\n")
		sb.WriteString("};\n\n")
	}

	// 域名特定转发
	for _, f := range domainForwards {
		domains := strings.Split(f.Domains, ",")
		for _, domain := range domains {
			domain = strings.TrimSpace(domain)
			if domain == "" {
				continue
			}
			sb.WriteString(fmt.Sprintf("zone \"%s\" {{\n", domain))
			sb.WriteString("    type forward;\n")
			sb.WriteString("    forward only;\n")
			sb.WriteString("    forwarders {\n")
			for _, ip := range strings.Split(f.Servers, ",") {
				ip = strings.TrimSpace(ip)
				if ip != "" {
					sb.WriteString(fmt.Sprintf("        %s;\n", ip))
				}
			}
			sb.WriteString("    };\n")
			sb.WriteString("};\n\n")
		}
	}

	// 写入配置文件
	forwarderConf := "/etc/bind/named.conf.forwarders"
	if err := os.WriteFile(forwarderConf, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write forwarders config: %w", err)
	}

	return nil
}
